<a href="https://colab.research.google.com/github/sellyrk/datamining2_inflasi_lakehouse/blob/main/DM2_AGREGASI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
BASE_PATH = "/content/drive/MyDrive/DM2_INFLASI"
RAW_PATH = f"{BASE_PATH}/data_lake/raw"
DB_PATH = f"{BASE_PATH}/warehouse/inflasi_dw.duckdb"

print(BASE_PATH)
print(RAW_PATH)
print(DB_PATH)

/content/drive/MyDrive/DM2_INFLASI
/content/drive/MyDrive/DM2_INFLASI/data_lake/raw
/content/drive/MyDrive/DM2_INFLASI/warehouse/inflasi_dw.duckdb

In [3]:
import os

for root, dirs, files in os.walk(RAW_PATH):
    level = root.replace(RAW_PATH, "").count(os.sep)
    indent = "    " * level
    print(f"{indent}{os.path.basename(root)}/")

    for file in files:
        print(f"{indent}    {file}")

raw/
    Pangan/
        Tabel Harga Berdasarkan Komoditas_Beras.xlsx
        Tabel Harga Berdasarkan Komoditas_Ayam.xlsx
        Tabel Harga Berdasarkan Komoditas_Daging.xlsx
        Tabel Harga Berdasarkan Komoditas_Telur.xlsx
        Tabel Harga Berdasarkan Komoditas_Bawang Merah.xlsx
        Tabel Harga Berdasarkan Komoditas_Cabai Merah.xlsx
        Tabel Harga Berdasarkan Komoditas_Minyak Goreng.xlsx
        Tabel Harga Berdasarkan Komoditas_Gula Pasir.xlsx
        Tabel Harga Berdasarkan Komoditas_Cabai Rawit.xlsx
        dim_komoditas.parquet
        fact_harga.parquet
    Ekonomi/
        Persentase Angkatan Kerja Terhadap Penduduk Usia Kerja (TPAK) menurut Provinsi, 2025.xlsx
        Rata-Rata Upah_Gaji (Triwulanan), 2025.xlsx
        Tingkat Pengangguran Terbuka Menurut Provinsi, 2025.xlsx
        Upah Minimum Provinsi (UMP) per Bulan Menurut Provinsi di Indonesia, 2025.xlsx
        fact_tpt.parquet
        fact_tpak.parquet
        fact_ump.parquet
        fact_upah_sektor_nasional.parquet
    Energi/
        Inflasi Bulanan (M-to-M) 38 Provinsi (2022=100) Menurut Kelompok dan Sub Kelompok 03 Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga, 2025.xlsx
        fact_inflasi_energi.parquet
    Sosial/
        Jumlah dan Persentase Penduduk Miskin Menurut Provinsi, 2025.xlsx
        Penduduk, Laju Pertumbuhan Penduduk, Distribusi Persentase Penduduk, Kepadatan Penduduk, Rasio Jenis Kelamin Penduduk Menurut Provinsi, 2025.xlsx
        Pengeluaran per Kapita yang Disesuaikan menurut Jenis Kelamin, 2025.xlsx
        fact_penduduk.parquet
        fact_pengeluaran_kapita.parquet
        fact_penduduk_miskin.parquet
    Bencana/
        fact_bencana_provinsi.parquet
        fact_bencana_nasional.parquet
        data_bencana_dampak_spesifik_2025.xlsx
    Inflasi/
        Inflasi Tahunan (Y-on-Y) 38 Provinsi (2022=100), 2025.xlsx
        fact_inflasi_yoy.parquet
    Data Umum/
        fact_inflasi_pangan_2025.csv
        fact_inflasi_pangan_2025.gsheet
    Dimensi/
        dim_provinsi.parquet
        dim_waktu.parquet

In [4]:
import glob
import os

files_xlsx = glob.glob(
    f"{RAW_PATH}/**/*.xlsx",
    recursive=True
)

print("Jumlah file XLSX:", len(files_xlsx))

for file in files_xlsx:
    print(file)

Jumlah file XLSX: 19
/content/drive/MyDrive/DM2_INFLASI/data_lake/raw/Pangan/Tabel Harga Berdasarkan Komoditas_Beras.xlsx
/content/drive/MyDrive/DM2_INFLASI/data_lake/raw/Pangan/Tabel Harga Berdasarkan Komoditas_Ayam.xlsx
/content/drive/MyDrive/DM2_INFLASI/data_lake/raw/Pangan/Tabel Harga Berdasarkan Komoditas_Daging.xlsx
/content/drive/MyDrive/DM2_INFLASI/data_lake/raw/Pangan/Tabel Harga Berdasarkan Komoditas_Telur.xlsx
/content/drive/MyDrive/DM2_INFLASI/data_lake/raw/Pangan/Tabel Harga Berdasarkan Komoditas_Bawang Merah.xlsx
/content/drive/MyDrive/DM2_INFLASI/data_lake/raw/Pangan/Tabel Harga Berdasarkan Komoditas_Cabai Merah.xlsx
/content/drive/MyDrive/DM2_INFLASI/data_lake/raw/Pangan/Tabel Harga Berdasarkan Komoditas_Minyak Goreng.xlsx
/content/drive/MyDrive/DM2_INFLASI/data_lake/raw/Pangan/Tabel Harga Berdasarkan Komoditas_Gula Pasir.xlsx
/content/drive/MyDrive/DM2_INFLASI/data_lake/raw/Pangan/Tabel Harga Berdasarkan Komoditas_Cabai Rawit.xlsx
/content/drive/MyDrive/DM2_INFLASI/data_lake/raw/Ekonomi/Persentase Angkatan Kerja Terhadap Penduduk Usia Kerja (TPAK) menurut Provinsi, 2025.xlsx
/content/drive/MyDrive/DM2_INFLASI/data_lake/raw/Ekonomi/Rata-Rata Upah_Gaji (Triwulanan), 2025.xlsx
/content/drive/MyDrive/DM2_INFLASI/data_lake/raw/Ekonomi/Tingkat Pengangguran Terbuka Menurut Provinsi, 2025.xlsx
/content/drive/MyDrive/DM2_INFLASI/data_lake/raw/Ekonomi/Upah Minimum Provinsi (UMP) per Bulan Menurut Provinsi di Indonesia, 2025.xlsx
/content/drive/MyDrive/DM2_INFLASI/data_lake/raw/Energi/Inflasi Bulanan (M-to-M) 38 Provinsi (2022=100) Menurut Kelompok dan Sub Kelompok 03 Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga, 2025.xlsx
/content/drive/MyDrive/DM2_INFLASI/data_lake/raw/Sosial/Jumlah dan Persentase Penduduk Miskin Menurut Provinsi, 2025.xlsx
/content/drive/MyDrive/DM2_INFLASI/data_lake/raw/Sosial/Penduduk, Laju Pertumbuhan Penduduk, Distribusi Persentase Penduduk, Kepadatan Penduduk, Rasio Jenis Kelamin Penduduk Menurut Provinsi, 2025.xlsx
/content/drive/MyDrive/DM2_INFLASI/data_lake/raw/Sosial/Pengeluaran per Kapita yang Disesuaikan menurut Jenis Kelamin, 2025.xlsx
/content/drive/MyDrive/DM2_INFLASI/data_lake/raw/Bencana/data_bencana_dampak_spesifik_2025.xlsx
/content/drive/MyDrive/DM2_INFLASI/data_lake/raw/Inflasi/Inflasi Tahunan (Y-on-Y) 38 Provinsi (2022=100), 2025.xlsx

In [5]:
import pandas as pd
import os

for file in files_xlsx:
    print("\n" + "="*80)
    print("FILE:", os.path.basename(file))

    excel = pd.ExcelFile(file)

    print("SHEET:", excel.sheet_names)

    for sheet in excel.sheet_names:
        df = pd.read_excel(file, sheet_name=sheet)

        print("\n---", sheet, "---")
        print("Shape:", df.shape)
        print("Kolom:", df.columns.tolist())
        display(df.head(3))

================================================================================
FILE: Tabel Harga Berdasarkan Komoditas_Beras.xlsx
SHEET: ['Sheet']

--- Sheet ---
Shape: (32, 14)
Kolom: ['No', 'Komoditas (Rp)', '01/ 01/ 2025', '03/ 02/ 2025', '03/ 03/ 2025', '01/ 04/ 2025', '01/ 05/ 2025', '02/ 06/ 2025', '01/ 07/ 2025', '01/ 08/ 2025', '01/ 09/ 2025', '01/ 10/ 2025', '03/ 11/ 2025', '01/ 12/ 2025']

,No,Komoditas (Rp),01/ 01/ 2025,03/ 02/ 2025,03/ 03/ 2025,01/ 04/ 2025,01/ 05/ 2025,02/ 06/ 2025,01/ 07/ 2025,01/ 08/ 2025,01/ 09/ 2025,01/ 10/ 2025,03/ 11/ 2025,01/ 12/ 2025
0,I,Semua Provinsi,"12,750","12,650","12,650","12,900","12,850","12,950","13,100","13,550","13,600","13,550","13,550","13,300"
1,II,Aceh,"13,250","13,300","13,100","13,200","13,350","13,650","14,250","15,150","15,150","14,200","14,400","14,100"
2,III,Sumatera Utara,"12,900","12,950","13,050","13,050","13,000","13,600","13,500","13,750","13,850","13,800","13,850","13,800"

================================================================================
FILE: Tabel Harga Berdasarkan Komoditas_Ayam.xlsx
SHEET: ['Sheet']

--- Sheet ---
Shape: (33, 14)
Kolom: ['No', 'Komoditas (Rp)', '01/ 01/ 2025', '03/ 02/ 2025', '03/ 03/ 2025', '01/ 04/ 2025', '01/ 05/ 2025', '02/ 06/ 2025', '01/ 07/ 2025', '01/ 08/ 2025', '01/ 09/ 2025', '01/ 10/ 2025', '03/ 11/ 2025', '01/ 12/ 2025']

,No,Komoditas (Rp),01/ 01/ 2025,03/ 02/ 2025,03/ 03/ 2025,01/ 04/ 2025,01/ 05/ 2025,02/ 06/ 2025,01/ 07/ 2025,01/ 08/ 2025,01/ 09/ 2025,01/ 10/ 2025,03/ 11/ 2025,01/ 12/ 2025
0,I,Semua Provinsi,"29,050","28,050","26,400","26,200","24,300","25,700","24,800","26,400","26,200","28,750","28,900","29,050"
1,II,Aceh,"26,650","25,400","23,300","22,250","22,900","22,850","21,900","22,650","24,700","26,050","25,850","28,050"
2,III,Sumatera Utara,"28,250","24,250","24,150","23,900","21,800","23,600","22,300","24,850","25,750","26,550","26,400","28,150"

================================================================================
FILE: Tabel Harga Berdasarkan Komoditas_Daging.xlsx
SHEET: ['Sheet']

--- Sheet ---
Shape: (30, 14)
Kolom: ['No', 'Komoditas (Rp)', '01/ 01/ 2025', '03/ 02/ 2025', '03/ 03/ 2025', '01/ 04/ 2025', '01/ 05/ 2025', '02/ 06/ 2025', '01/ 07/ 2025', '01/ 08/ 2025', '01/ 09/ 2025', '01/ 10/ 2025', '03/ 11/ 2025', '01/ 12/ 2025']

,No,Komoditas (Rp),01/ 01/ 2025,03/ 02/ 2025,03/ 03/ 2025,01/ 04/ 2025,01/ 05/ 2025,02/ 06/ 2025,01/ 07/ 2025,01/ 08/ 2025,01/ 09/ 2025,01/ 10/ 2025,03/ 11/ 2025,01/ 12/ 2025
0,I,Semua Provinsi,"122,950","120,750","121,450","123,900","124,200","124,250","124,250","124,100","123,850","124,000","124,250","124,450"
1,II,Aceh,"144,800","144,800","147,100","143,800","146,550","141,450","143,350","143,350","143,750","144,600","144,200","144,200"
2,III,Sumatera Utara,"125,000","122,800","121,650","123,350","122,200","125,000","122,200","121,100","120,000","120,000","123,350","120,550"

================================================================================
FILE: Tabel Harga Berdasarkan Komoditas_Telur.xlsx
SHEET: ['Sheet']

--- Sheet ---
Shape: (33, 14)
Kolom: ['No', 'Komoditas (Rp)', '01/ 01/ 2025', '03/ 02/ 2025', '03/ 03/ 2025', '01/ 04/ 2025', '01/ 05/ 2025', '02/ 06/ 2025', '01/ 07/ 2025', '01/ 08/ 2025', '01/ 09/ 2025', '01/ 10/ 2025', '03/ 11/ 2025', '01/ 12/ 2025']

,No,Komoditas (Rp),01/ 01/ 2025,03/ 02/ 2025,03/ 03/ 2025,01/ 04/ 2025,01/ 05/ 2025,02/ 06/ 2025,01/ 07/ 2025,01/ 08/ 2025,01/ 09/ 2025,01/ 10/ 2025,03/ 11/ 2025,01/ 12/ 2025
0,I,Semua Provinsi,"28,350","27,250","27,050","26,650","26,000","25,800","26,250","26,650","26,300","26,850","27,650","27,750"
1,II,Aceh,"28,950","26,400","25,900","23,750","23,900","24,800","25,450","26,700","26,900","27,100","28,750","29,250"
2,III,Sumatera Utara,"26,550","24,000","24,300","23,200","22,200","20,750","21,600","24,950","24,350","25,450","24,200","26,350"

================================================================================
FILE: Tabel Harga Berdasarkan Komoditas_Bawang Merah.xlsx
SHEET: ['Sheet']

--- Sheet ---
Shape: (24, 14)
Kolom: ['No', 'Komoditas (Rp)', '01/ 01/ 2025', '03/ 02/ 2025', '03/ 03/ 2025', '01/ 04/ 2025', '01/ 05/ 2025', '02/ 06/ 2025', '01/ 07/ 2025', '01/ 08/ 2025', '01/ 09/ 2025', '01/ 10/ 2025', '03/ 11/ 2025', '01/ 12/ 2025']

,No,Komoditas (Rp),01/ 01/ 2025,03/ 02/ 2025,03/ 03/ 2025,01/ 04/ 2025,01/ 05/ 2025,02/ 06/ 2025,01/ 07/ 2025,01/ 08/ 2025,01/ 09/ 2025,01/ 10/ 2025,03/ 11/ 2025,01/ 12/ 2025
0,I,Semua Provinsi,"31,400","25,550","23,750","31,650","32,550","26,750","32,100","33,900","36,500","29,850","29,100","29,850"
1,II,Aceh,"29,150","33,150","31,400","31,250","26,750","30,400","30,400","36,750","40,450","33,200","24,700","24,250"
2,III,Sumatera Utara,"27,500","24,850","20,750","24,500","25,400","21,650","25,100","31,100","25,000","25,200","23,000","24,800"

================================================================================
FILE: Tabel Harga Berdasarkan Komoditas_Cabai Merah.xlsx
SHEET: ['Sheet']

--- Sheet ---
Shape: (33, 14)
Kolom: ['No', 'Komoditas (Rp)', '01/ 01/ 2025', '03/ 02/ 2025', '03/ 03/ 2025', '01/ 04/ 2025', '01/ 05/ 2025', '02/ 06/ 2025', '01/ 07/ 2025', '01/ 08/ 2025', '01/ 09/ 2025', '01/ 10/ 2025', '03/ 11/ 2025', '01/ 12/ 2025']

,No,Komoditas (Rp),01/ 01/ 2025,03/ 02/ 2025,03/ 03/ 2025,01/ 04/ 2025,01/ 05/ 2025,02/ 06/ 2025,01/ 07/ 2025,01/ 08/ 2025,01/ 09/ 2025,01/ 10/ 2025,03/ 11/ 2025,01/ 12/ 2025
0,I,Semua Provinsi,"26,450","39,150","36,550","36,200","40,900","31,850","30,700","33,100","29,100","39,150","36,900","36,900"
1,II,Aceh,"28,100","41,600","38,100","30,850","45,950","20,300","18,600","19,800","29,000","47,150","48,250","30,850"
2,III,Sumatera Utara,"28,850","41,850","31,250","25,500","41,000","18,150","14,200","16,050","23,700","69,050","64,600","37,800"

================================================================================
FILE: Tabel Harga Berdasarkan Komoditas_Minyak Goreng.xlsx
SHEET: ['Sheet']

--- Sheet ---
Shape: (15, 14)
Kolom: ['No', 'Komoditas (Rp)', '01/ 01/ 2025', '03/ 02/ 2025', '03/ 03/ 2025', '01/ 04/ 2025', '01/ 05/ 2025', '02/ 06/ 2025', '01/ 07/ 2025', '01/ 08/ 2025', '01/ 09/ 2025', '01/ 10/ 2025', '03/ 11/ 2025', '01/ 12/ 2025']

,No,Komoditas (Rp),01/ 01/ 2025,03/ 02/ 2025,03/ 03/ 2025,01/ 04/ 2025,01/ 05/ 2025,02/ 06/ 2025,01/ 07/ 2025,01/ 08/ 2025,01/ 09/ 2025,01/ 10/ 2025,03/ 11/ 2025,01/ 12/ 2025
0,I,Semua Provinsi,"18,050","18,400","17,950","18,000","17,950","17,650","17,600","17,650","17,700","17,650","17,750","17,850"
1,II,Aceh,"20,450","21,400","21,700","20,900","19,350","18,000","19,350","19,450","19,500","19,550","19,600","19,300"
2,III,Sumatera Utara,"17,350","17,450","17,800","17,800","17,500","17,500","17,100","17,100","17,100","17,100","17,100","17,100"

================================================================================
FILE: Tabel Harga Berdasarkan Komoditas_Gula Pasir.xlsx
SHEET: ['Sheet']

--- Sheet ---
Shape: (14, 14)
Kolom: ['No', 'Komoditas (Rp)', '01/ 01/ 2025', '03/ 02/ 2025', '03/ 03/ 2025', '01/ 04/ 2025', '01/ 05/ 2025', '02/ 06/ 2025', '01/ 07/ 2025', '01/ 08/ 2025', '01/ 09/ 2025', '01/ 10/ 2025', '03/ 11/ 2025', '01/ 12/ 2025']

,No,Komoditas (Rp),01/ 01/ 2025,03/ 02/ 2025,03/ 03/ 2025,01/ 04/ 2025,01/ 05/ 2025,02/ 06/ 2025,01/ 07/ 2025,01/ 08/ 2025,01/ 09/ 2025,01/ 10/ 2025,03/ 11/ 2025,01/ 12/ 2025
0,I,Semua Provinsi,"15,850","16,150","16,300","16,650","16,650","16,400","16,100","15,850","15,850","15,900","15,900","15,950"
1,II,Aceh,"17,750","17,650","18,050","19,000","18,900","17,750","17,500","17,100","17,350","17,650","17,450","17,200"
2,III,Sumatera Selatan,"15,100","15,500","15,500","16,000","16,000","16,000","16,000","14,600","14,600","14,600","14,600","14,800"

================================================================================
FILE: Tabel Harga Berdasarkan Komoditas_Cabai Rawit.xlsx
SHEET: ['Sheet']

--- Sheet ---
Shape: (32, 14)
Kolom: ['No', 'Komoditas (Rp)', '01/ 01/ 2025', '03/ 02/ 2025', '03/ 03/ 2025', '01/ 04/ 2025', '01/ 05/ 2025', '02/ 06/ 2025', '01/ 07/ 2025', '01/ 08/ 2025', '01/ 09/ 2025', '01/ 10/ 2025', '03/ 11/ 2025', '01/ 12/ 2025']

,No,Komoditas (Rp),01/ 01/ 2025,03/ 02/ 2025,03/ 03/ 2025,01/ 04/ 2025,01/ 05/ 2025,02/ 06/ 2025,01/ 07/ 2025,01/ 08/ 2025,01/ 09/ 2025,01/ 10/ 2025,03/ 11/ 2025,01/ 12/ 2025
0,I,Semua Provinsi,"31,750","47,000","47,700","53,800","48,850","33,500","37,500","43,900","34,150","35,200","27,250","29,500"
1,II,Aceh,"33,450","39,700","41,450","31,350","30,550","25,200","23,200","16,150","31,150","41,200","24,450","23,750"
2,III,Sumatera Utara,"35,350","42,650","38,450","28,100","28,200","17,500","16,000","20,100","34,450","41,300","33,500","23,550"

================================================================================
FILE: Persentase Angkatan Kerja Terhadap Penduduk Usia Kerja (TPAK) menurut Provinsi, 2025.xlsx
SHEET: ['Sheet1']

--- Sheet1 ---
Shape: (39, 3)
Kolom: ['38 Provinsi', 'Februari', 'Agustus']

      38 Provinsi  Februari  Agustus
0            ACEH     65.63    65.32
1  SUMATERA UTARA     70.13    72.29
2  SUMATERA BARAT     70.95    71.34

================================================================================
FILE: Rata-Rata Upah_Gaji (Triwulanan), 2025.xlsx
SHEET: ['Sheet1']

--- Sheet1 ---
Shape: (18, 5)
Kolom: ['17 sektor', 'Februari', 'Mei', 'Agustus', 'November']

  17 sektor  Februari Mei  Agustus  November
0         A   2247459   -  2540158   2475338
1         B   5086094   -  4983713   4866702
2         C   3090532   -  3270191   3311920

================================================================================
FILE: Tingkat Pengangguran Terbuka Menurut Provinsi, 2025.xlsx
SHEET: ['Sheet1']

--- Sheet1 ---
Shape: (39, 4)
Kolom: ['38 Provinsi', 'Februari', 'Agustus', 'Tahunan']

      38 Provinsi  Februari  Agustus Tahunan
0            ACEH      5.50     5.64       -
1  SUMATERA UTARA      5.05     5.32       -
2  SUMATERA BARAT      5.69     5.62       -

================================================================================
FILE: Upah Minimum Provinsi (UMP) per Bulan Menurut Provinsi di Indonesia, 2025.xlsx
SHEET: ['Sheet1']

--- Sheet1 ---
Shape: (38, 2)
Kolom: ['Provinsi di Indonesia', '2025']

  Provinsi di Indonesia     2025
0               11 Aceh  3685616
1     12 Sumatera Utara  2992559
2     13 Sumatera Barat  2994193

================================================================================
FILE: Inflasi Bulanan (M-to-M) 38 Provinsi (2022=100) Menurut Kelompok dan Sub Kelompok 03 Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga, 2025.xlsx
SHEET: ['Sheet1']

--- Sheet1 ---
Shape: (39, 66)
Kolom: ['38 Provinsi (2022=100)', 'Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember', 'Tahunan', 'Januari.1', 'Februari.1', 'Maret.1', 'April.1', 'Mei.1', 'Juni.1', 'Juli.1', 'Agustus.1', 'September.1', 'Oktober.1', 'November.1', 'Desember.1', 'Tahunan.1', 'Januari.2', 'Februari.2', 'Maret.2', 'April.2', 'Mei.2', 'Juni.2', 'Juli.2', 'Agustus.2', 'September.2', 'Oktober.2', 'November.2', 'Desember.2', 'Tahunan.2', 'Januari.3', 'Februari.3', 'Maret.3', 'April.3', 'Mei.3', 'Juni.3', 'Juli.3', 'Agustus.3', 'September.3', 'Oktober.3', 'November.3', 'Desember.3', 'Tahunan.3', 'Januari.4', 'Februari.4', 'Maret.4', 'April.4', 'Mei.4', 'Juni.4', 'Juli.4', 'Agustus.4', 'September.4', 'Oktober.4', 'November.4', 'Desember.4', 'Tahunan.4']

,38 Provinsi (2022=100),Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,...,April.4,Mei.4,Juni.4,Juli.4,Agustus.4,September.4,Oktober.4,November.4,Desember.4,Tahunan.4
0,PROV ACEH,-9.97,-3.73,9.25,5.86,0.10,-0.09,0.04,0.01,0.00,...,15.30,0.03,-0.19,0.11,0.00,0.02,0.01,0.00,3.99,-
1,PROV SUMATERA UTARA,-7.11,-4.26,6.16,6.09,0.09,0.15,0.06,0.03,0.00,...,19.77,0.17,0.03,0.03,-0.05,-0.02,0.04,-0.22,0.04,-
2,PROV SUMATERA BARAT,-7.56,-1.74,7.18,3.72,0.01,0.13,0.02,0.03,0.06,...,17.10,0.00,0.00,0.00,-0.02,-0.04,0.00,0.00,0.03,-

================================================================================
FILE: Jumlah dan Persentase Penduduk Miskin Menurut Provinsi, 2025.xlsx
SHEET: ['Sheet1']

--- Sheet1 ---
Shape: (46, 8)
Kolom: ['Provinsi', 'Garis Kemiskinan - Maret (Rp)', 'Garis Kemiskinan - September (Rp)', 'Jumlah Penduduk Miskin - Maret (ribu) (Ribu)', 'Jumlah Penduduk Miskin - September (ribu) (Ribu)', 'Persentase Penduduk Miskin - Maret', 'Persentase Penduduk Miskin - September', 'Unnamed: 7']

,Provinsi,Garis Kemiskinan - Maret (Rp),Garis Kemiskinan - September (Rp),Jumlah Penduduk Miskin - Maret (ribu) (Ribu),Jumlah Penduduk Miskin - September (ribu) (Ribu),Persentase Penduduk Miskin - Maret,Persentase Penduduk Miskin - September,Unnamed: 7
0,Aceh,676247,715103,704.69,703.33,12.33,12.22,NaN
1,Sumatera Utara,666546,718220,1140.25,1128.06,7.36,7.24,NaN
2,Sumatera Barat,729806,776517,312.35,312.3,5.35,5.31,NaN

================================================================================
FILE: Penduduk, Laju Pertumbuhan Penduduk, Distribusi Persentase Penduduk, Kepadatan Penduduk, Rasio Jenis Kelamin Penduduk Menurut Provinsi, 2025.xlsx
SHEET: ['Sheet1']

--- Sheet1 ---
Shape: (52, 8)
Kolom: ['Provinsi', 'Jumlah Penduduk (Ribu)', 'Laju Pertumbuhan Penduduk per Tahun', 'Persentase Penduduk', 'Kepadatan Penduduk per km persegi (Km2)', 'Rasio Jenis Kelamin Penduduk', 'Unnamed: 6', 'Unnamed: 7']

,Provinsi,Jumlah Penduduk (Ribu),Laju Pertumbuhan Penduduk per Tahun,Persentase Penduduk,Kepadatan Penduduk per km persegi (Km2),Rasio Jenis Kelamin Penduduk,Unnamed: 6,Unnamed: 7
0,Aceh,5626,1.37,1.98,99,100.9,NaN,NaN
1,Sumatera Utara,15785.8,1.37,5.55,218,100.8,NaN,NaN
2,Sumatera Barat,5914.3,1.41,2.08,140,101.5,NaN,NaN

================================================================================
FILE: Pengeluaran per Kapita yang Disesuaikan menurut Jenis Kelamin, 2025.xlsx
SHEET: ['Sheet1']

--- Sheet1 ---
Shape: (582, 3)
Kolom: ['Provinsi/Kabupaten/Kota/Indonesia', 'Unnamed: 1', 'Unnamed: 2']

,Provinsi/Kabupaten/Kota/Indonesia,Unnamed: 1,Unnamed: 2
0,NaN,Pengeluaran per Kapita yang Disesuaikan menuru...,NaN
1,NaN,Laki-laki,Perempuan
2,NaN,2025,2025

================================================================================
FILE: data_bencana_dampak_spesifik_2025.xlsx
SHEET: ['data_bencana_dampak_spesifik_20']

--- data_bencana_dampak_spesifik_20 ---
Shape: (396, 11)
Kolom: ['Provinsi', 'Bulan', 'Tahun', 'Jenis Bencana', 'Jumlah Kejadian', 'Korban Meninggal (Jiwa)', 'Korban Hilang (Jiwa)', 'Korban Luka (Jiwa)', 'Korban Terdampak (Jiwa)', 'Korban Mengungsi (Jiwa)', 'Rumah Rusak (Unit)']

,Provinsi,Bulan,Tahun,Jenis Bencana,Jumlah Kejadian,Korban Meninggal (Jiwa),Korban Hilang (Jiwa),Korban Luka (Jiwa),Korban Terdampak (Jiwa),Korban Mengungsi (Jiwa),Rumah Rusak (Unit)
0,Aceh,Januari,2025,Banjir,3,0,0,6,840,204,30
1,Aceh,Januari,2025,Tanah Longsor,1,0,0,1,82,13,9
2,Aceh,Februari,2025,Banjir,2,0,0,2,722,135,8

================================================================================
FILE: Inflasi Tahunan (Y-on-Y) 38 Provinsi (2022=100), 2025.xlsx
SHEET: ['Sheet1']

--- Sheet1 ---
Shape: (39, 14)
Kolom: ['38 Provinsi (2022=100)', 'Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember', 'Tahunan']

,38 Provinsi (2022=100),Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan
0,PROV ACEH,1.61,0.41,1.53,3.11,2.35,2.19,3.00,3.70,4.45,4.66,3.58,6.71,-
1,PROV SUMATERA UTARA,1.78,0.73,0.69,2.09,1.11,1.25,2.86,4.42,5.32,4.97,3.96,4.66,-
2,PROV SUMATERA BARAT,1.24,-0.09,0.30,2.38,0.85,0.45,2.19,2.89,4.22,4.52,3.98,5.15,-

In [6]:
import glob
import os
import pandas as pd

files_xlsx = glob.glob(
    f"{RAW_PATH}/**/*.xlsx",
    recursive=True
)

print("Jumlah file:", len(files_xlsx))

for file in files_xlsx:

    print("\n" + "="*100)
    print("FILE:", os.path.basename(file))
    print("="*100)

    try:
        excel = pd.ExcelFile(file)

        print("Sheet:", excel.sheet_names)

        for sheet in excel.sheet_names:

            df = pd.read_excel(
                file,
                sheet_name=sheet
            )

            print("\n--- SHEET:", sheet, "---")
            print("Shape:", df.shape)
            print("Kolom:")
            print(df.columns.tolist())

            display(df.head(3))

    except Exception as e:
        print("ERROR:", e)

Jumlah file: 19

====================================================================================================
FILE: Tabel Harga Berdasarkan Komoditas_Beras.xlsx
====================================================================================================
Sheet: ['Sheet']

--- SHEET: Sheet ---
Shape: (32, 14)
Kolom:
['No', 'Komoditas (Rp)', '01/ 01/ 2025', '03/ 02/ 2025', '03/ 03/ 2025', '01/ 04/ 2025', '01/ 05/ 2025', '02/ 06/ 2025', '01/ 07/ 2025', '01/ 08/ 2025', '01/ 09/ 2025', '01/ 10/ 2025', '03/ 11/ 2025', '01/ 12/ 2025']

,No,Komoditas (Rp),01/ 01/ 2025,03/ 02/ 2025,03/ 03/ 2025,01/ 04/ 2025,01/ 05/ 2025,02/ 06/ 2025,01/ 07/ 2025,01/ 08/ 2025,01/ 09/ 2025,01/ 10/ 2025,03/ 11/ 2025,01/ 12/ 2025
0,I,Semua Provinsi,"12,750","12,650","12,650","12,900","12,850","12,950","13,100","13,550","13,600","13,550","13,550","13,300"
1,II,Aceh,"13,250","13,300","13,100","13,200","13,350","13,650","14,250","15,150","15,150","14,200","14,400","14,100"
2,III,Sumatera Utara,"12,900","12,950","13,050","13,050","13,000","13,600","13,500","13,750","13,850","13,800","13,850","13,800"

====================================================================================================
FILE: Tabel Harga Berdasarkan Komoditas_Ayam.xlsx
====================================================================================================
Sheet: ['Sheet']

--- SHEET: Sheet ---
Shape: (33, 14)
Kolom:
['No', 'Komoditas (Rp)', '01/ 01/ 2025', '03/ 02/ 2025', '03/ 03/ 2025', '01/ 04/ 2025', '01/ 05/ 2025', '02/ 06/ 2025', '01/ 07/ 2025', '01/ 08/ 2025', '01/ 09/ 2025', '01/ 10/ 2025', '03/ 11/ 2025', '01/ 12/ 2025']

,No,Komoditas (Rp),01/ 01/ 2025,03/ 02/ 2025,03/ 03/ 2025,01/ 04/ 2025,01/ 05/ 2025,02/ 06/ 2025,01/ 07/ 2025,01/ 08/ 2025,01/ 09/ 2025,01/ 10/ 2025,03/ 11/ 2025,01/ 12/ 2025
0,I,Semua Provinsi,"29,050","28,050","26,400","26,200","24,300","25,700","24,800","26,400","26,200","28,750","28,900","29,050"
1,II,Aceh,"26,650","25,400","23,300","22,250","22,900","22,850","21,900","22,650","24,700","26,050","25,850","28,050"
2,III,Sumatera Utara,"28,250","24,250","24,150","23,900","21,800","23,600","22,300","24,850","25,750","26,550","26,400","28,150"

====================================================================================================
FILE: Tabel Harga Berdasarkan Komoditas_Daging.xlsx
====================================================================================================
Sheet: ['Sheet']

--- SHEET: Sheet ---
Shape: (30, 14)
Kolom:
['No', 'Komoditas (Rp)', '01/ 01/ 2025', '03/ 02/ 2025', '03/ 03/ 2025', '01/ 04/ 2025', '01/ 05/ 2025', '02/ 06/ 2025', '01/ 07/ 2025', '01/ 08/ 2025', '01/ 09/ 2025', '01/ 10/ 2025', '03/ 11/ 2025', '01/ 12/ 2025']

,No,Komoditas (Rp),01/ 01/ 2025,03/ 02/ 2025,03/ 03/ 2025,01/ 04/ 2025,01/ 05/ 2025,02/ 06/ 2025,01/ 07/ 2025,01/ 08/ 2025,01/ 09/ 2025,01/ 10/ 2025,03/ 11/ 2025,01/ 12/ 2025
0,I,Semua Provinsi,"122,950","120,750","121,450","123,900","124,200","124,250","124,250","124,100","123,850","124,000","124,250","124,450"
1,II,Aceh,"144,800","144,800","147,100","143,800","146,550","141,450","143,350","143,350","143,750","144,600","144,200","144,200"
2,III,Sumatera Utara,"125,000","122,800","121,650","123,350","122,200","125,000","122,200","121,100","120,000","120,000","123,350","120,550"

====================================================================================================
FILE: Tabel Harga Berdasarkan Komoditas_Telur.xlsx
====================================================================================================
Sheet: ['Sheet']

--- SHEET: Sheet ---
Shape: (33, 14)
Kolom:
['No', 'Komoditas (Rp)', '01/ 01/ 2025', '03/ 02/ 2025', '03/ 03/ 2025', '01/ 04/ 2025', '01/ 05/ 2025', '02/ 06/ 2025', '01/ 07/ 2025', '01/ 08/ 2025', '01/ 09/ 2025', '01/ 10/ 2025', '03/ 11/ 2025', '01/ 12/ 2025']

,No,Komoditas (Rp),01/ 01/ 2025,03/ 02/ 2025,03/ 03/ 2025,01/ 04/ 2025,01/ 05/ 2025,02/ 06/ 2025,01/ 07/ 2025,01/ 08/ 2025,01/ 09/ 2025,01/ 10/ 2025,03/ 11/ 2025,01/ 12/ 2025
0,I,Semua Provinsi,"28,350","27,250","27,050","26,650","26,000","25,800","26,250","26,650","26,300","26,850","27,650","27,750"
1,II,Aceh,"28,950","26,400","25,900","23,750","23,900","24,800","25,450","26,700","26,900","27,100","28,750","29,250"
2,III,Sumatera Utara,"26,550","24,000","24,300","23,200","22,200","20,750","21,600","24,950","24,350","25,450","24,200","26,350"

====================================================================================================
FILE: Tabel Harga Berdasarkan Komoditas_Bawang Merah.xlsx
====================================================================================================
Sheet: ['Sheet']

--- SHEET: Sheet ---
Shape: (24, 14)
Kolom:
['No', 'Komoditas (Rp)', '01/ 01/ 2025', '03/ 02/ 2025', '03/ 03/ 2025', '01/ 04/ 2025', '01/ 05/ 2025', '02/ 06/ 2025', '01/ 07/ 2025', '01/ 08/ 2025', '01/ 09/ 2025', '01/ 10/ 2025', '03/ 11/ 2025', '01/ 12/ 2025']

,No,Komoditas (Rp),01/ 01/ 2025,03/ 02/ 2025,03/ 03/ 2025,01/ 04/ 2025,01/ 05/ 2025,02/ 06/ 2025,01/ 07/ 2025,01/ 08/ 2025,01/ 09/ 2025,01/ 10/ 2025,03/ 11/ 2025,01/ 12/ 2025
0,I,Semua Provinsi,"31,400","25,550","23,750","31,650","32,550","26,750","32,100","33,900","36,500","29,850","29,100","29,850"
1,II,Aceh,"29,150","33,150","31,400","31,250","26,750","30,400","30,400","36,750","40,450","33,200","24,700","24,250"
2,III,Sumatera Utara,"27,500","24,850","20,750","24,500","25,400","21,650","25,100","31,100","25,000","25,200","23,000","24,800"

====================================================================================================
FILE: Tabel Harga Berdasarkan Komoditas_Cabai Merah.xlsx
====================================================================================================
Sheet: ['Sheet']

--- SHEET: Sheet ---
Shape: (33, 14)
Kolom:
['No', 'Komoditas (Rp)', '01/ 01/ 2025', '03/ 02/ 2025', '03/ 03/ 2025', '01/ 04/ 2025', '01/ 05/ 2025', '02/ 06/ 2025', '01/ 07/ 2025', '01/ 08/ 2025', '01/ 09/ 2025', '01/ 10/ 2025', '03/ 11/ 2025', '01/ 12/ 2025']

,No,Komoditas (Rp),01/ 01/ 2025,03/ 02/ 2025,03/ 03/ 2025,01/ 04/ 2025,01/ 05/ 2025,02/ 06/ 2025,01/ 07/ 2025,01/ 08/ 2025,01/ 09/ 2025,01/ 10/ 2025,03/ 11/ 2025,01/ 12/ 2025
0,I,Semua Provinsi,"26,450","39,150","36,550","36,200","40,900","31,850","30,700","33,100","29,100","39,150","36,900","36,900"
1,II,Aceh,"28,100","41,600","38,100","30,850","45,950","20,300","18,600","19,800","29,000","47,150","48,250","30,850"
2,III,Sumatera Utara,"28,850","41,850","31,250","25,500","41,000","18,150","14,200","16,050","23,700","69,050","64,600","37,800"

====================================================================================================
FILE: Tabel Harga Berdasarkan Komoditas_Minyak Goreng.xlsx
====================================================================================================
Sheet: ['Sheet']

--- SHEET: Sheet ---
Shape: (15, 14)
Kolom:
['No', 'Komoditas (Rp)', '01/ 01/ 2025', '03/ 02/ 2025', '03/ 03/ 2025', '01/ 04/ 2025', '01/ 05/ 2025', '02/ 06/ 2025', '01/ 07/ 2025', '01/ 08/ 2025', '01/ 09/ 2025', '01/ 10/ 2025', '03/ 11/ 2025', '01/ 12/ 2025']

,No,Komoditas (Rp),01/ 01/ 2025,03/ 02/ 2025,03/ 03/ 2025,01/ 04/ 2025,01/ 05/ 2025,02/ 06/ 2025,01/ 07/ 2025,01/ 08/ 2025,01/ 09/ 2025,01/ 10/ 2025,03/ 11/ 2025,01/ 12/ 2025
0,I,Semua Provinsi,"18,050","18,400","17,950","18,000","17,950","17,650","17,600","17,650","17,700","17,650","17,750","17,850"
1,II,Aceh,"20,450","21,400","21,700","20,900","19,350","18,000","19,350","19,450","19,500","19,550","19,600","19,300"
2,III,Sumatera Utara,"17,350","17,450","17,800","17,800","17,500","17,500","17,100","17,100","17,100","17,100","17,100","17,100"

====================================================================================================
FILE: Tabel Harga Berdasarkan Komoditas_Gula Pasir.xlsx
====================================================================================================
Sheet: ['Sheet']

--- SHEET: Sheet ---
Shape: (14, 14)
Kolom:
['No', 'Komoditas (Rp)', '01/ 01/ 2025', '03/ 02/ 2025', '03/ 03/ 2025', '01/ 04/ 2025', '01/ 05/ 2025', '02/ 06/ 2025', '01/ 07/ 2025', '01/ 08/ 2025', '01/ 09/ 2025', '01/ 10/ 2025', '03/ 11/ 2025', '01/ 12/ 2025']

,No,Komoditas (Rp),01/ 01/ 2025,03/ 02/ 2025,03/ 03/ 2025,01/ 04/ 2025,01/ 05/ 2025,02/ 06/ 2025,01/ 07/ 2025,01/ 08/ 2025,01/ 09/ 2025,01/ 10/ 2025,03/ 11/ 2025,01/ 12/ 2025
0,I,Semua Provinsi,"15,850","16,150","16,300","16,650","16,650","16,400","16,100","15,850","15,850","15,900","15,900","15,950"
1,II,Aceh,"17,750","17,650","18,050","19,000","18,900","17,750","17,500","17,100","17,350","17,650","17,450","17,200"
2,III,Sumatera Selatan,"15,100","15,500","15,500","16,000","16,000","16,000","16,000","14,600","14,600","14,600","14,600","14,800"

====================================================================================================
FILE: Tabel Harga Berdasarkan Komoditas_Cabai Rawit.xlsx
====================================================================================================
Sheet: ['Sheet']

--- SHEET: Sheet ---
Shape: (32, 14)
Kolom:
['No', 'Komoditas (Rp)', '01/ 01/ 2025', '03/ 02/ 2025', '03/ 03/ 2025', '01/ 04/ 2025', '01/ 05/ 2025', '02/ 06/ 2025', '01/ 07/ 2025', '01/ 08/ 2025', '01/ 09/ 2025', '01/ 10/ 2025', '03/ 11/ 2025', '01/ 12/ 2025']

,No,Komoditas (Rp),01/ 01/ 2025,03/ 02/ 2025,03/ 03/ 2025,01/ 04/ 2025,01/ 05/ 2025,02/ 06/ 2025,01/ 07/ 2025,01/ 08/ 2025,01/ 09/ 2025,01/ 10/ 2025,03/ 11/ 2025,01/ 12/ 2025
0,I,Semua Provinsi,"31,750","47,000","47,700","53,800","48,850","33,500","37,500","43,900","34,150","35,200","27,250","29,500"
1,II,Aceh,"33,450","39,700","41,450","31,350","30,550","25,200","23,200","16,150","31,150","41,200","24,450","23,750"
2,III,Sumatera Utara,"35,350","42,650","38,450","28,100","28,200","17,500","16,000","20,100","34,450","41,300","33,500","23,550"

====================================================================================================
FILE: Persentase Angkatan Kerja Terhadap Penduduk Usia Kerja (TPAK) menurut Provinsi, 2025.xlsx
====================================================================================================
Sheet: ['Sheet1']

--- SHEET: Sheet1 ---
Shape: (39, 3)
Kolom:
['38 Provinsi', 'Februari', 'Agustus']

      38 Provinsi  Februari  Agustus
0            ACEH     65.63    65.32
1  SUMATERA UTARA     70.13    72.29
2  SUMATERA BARAT     70.95    71.34

====================================================================================================
FILE: Rata-Rata Upah_Gaji (Triwulanan), 2025.xlsx
====================================================================================================
Sheet: ['Sheet1']

--- SHEET: Sheet1 ---
Shape: (18, 5)
Kolom:
['17 sektor', 'Februari', 'Mei', 'Agustus', 'November']

  17 sektor  Februari Mei  Agustus  November
0         A   2247459   -  2540158   2475338
1         B   5086094   -  4983713   4866702
2         C   3090532   -  3270191   3311920

====================================================================================================
FILE: Tingkat Pengangguran Terbuka Menurut Provinsi, 2025.xlsx
====================================================================================================
Sheet: ['Sheet1']

--- SHEET: Sheet1 ---
Shape: (39, 4)
Kolom:
['38 Provinsi', 'Februari', 'Agustus', 'Tahunan']

      38 Provinsi  Februari  Agustus Tahunan
0            ACEH      5.50     5.64       -
1  SUMATERA UTARA      5.05     5.32       -
2  SUMATERA BARAT      5.69     5.62       -

====================================================================================================
FILE: Upah Minimum Provinsi (UMP) per Bulan Menurut Provinsi di Indonesia, 2025.xlsx
====================================================================================================
Sheet: ['Sheet1']

--- SHEET: Sheet1 ---
Shape: (38, 2)
Kolom:
['Provinsi di Indonesia', '2025']

  Provinsi di Indonesia     2025
0               11 Aceh  3685616
1     12 Sumatera Utara  2992559
2     13 Sumatera Barat  2994193

====================================================================================================
FILE: Inflasi Bulanan (M-to-M) 38 Provinsi (2022=100) Menurut Kelompok dan Sub Kelompok 03 Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga, 2025.xlsx
====================================================================================================
Sheet: ['Sheet1']

--- SHEET: Sheet1 ---
Shape: (39, 66)
Kolom:
['38 Provinsi (2022=100)', 'Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember', 'Tahunan', 'Januari.1', 'Februari.1', 'Maret.1', 'April.1', 'Mei.1', 'Juni.1', 'Juli.1', 'Agustus.1', 'September.1', 'Oktober.1', 'November.1', 'Desember.1', 'Tahunan.1', 'Januari.2', 'Februari.2', 'Maret.2', 'April.2', 'Mei.2', 'Juni.2', 'Juli.2', 'Agustus.2', 'September.2', 'Oktober.2', 'November.2', 'Desember.2', 'Tahunan.2', 'Januari.3', 'Februari.3', 'Maret.3', 'April.3', 'Mei.3', 'Juni.3', 'Juli.3', 'Agustus.3', 'September.3', 'Oktober.3', 'November.3', 'Desember.3', 'Tahunan.3', 'Januari.4', 'Februari.4', 'Maret.4', 'April.4', 'Mei.4', 'Juni.4', 'Juli.4', 'Agustus.4', 'September.4', 'Oktober.4', 'November.4', 'Desember.4', 'Tahunan.4']

,38 Provinsi (2022=100),Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,...,April.4,Mei.4,Juni.4,Juli.4,Agustus.4,September.4,Oktober.4,November.4,Desember.4,Tahunan.4
0,PROV ACEH,-9.97,-3.73,9.25,5.86,0.10,-0.09,0.04,0.01,0.00,...,15.30,0.03,-0.19,0.11,0.00,0.02,0.01,0.00,3.99,-
1,PROV SUMATERA UTARA,-7.11,-4.26,6.16,6.09,0.09,0.15,0.06,0.03,0.00,...,19.77,0.17,0.03,0.03,-0.05,-0.02,0.04,-0.22,0.04,-
2,PROV SUMATERA BARAT,-7.56,-1.74,7.18,3.72,0.01,0.13,0.02,0.03,0.06,...,17.10,0.00,0.00,0.00,-0.02,-0.04,0.00,0.00,0.03,-

====================================================================================================
FILE: Jumlah dan Persentase Penduduk Miskin Menurut Provinsi, 2025.xlsx
====================================================================================================
Sheet: ['Sheet1']

--- SHEET: Sheet1 ---
Shape: (46, 8)
Kolom:
['Provinsi', 'Garis Kemiskinan - Maret (Rp)', 'Garis Kemiskinan - September (Rp)', 'Jumlah Penduduk Miskin - Maret (ribu) (Ribu)', 'Jumlah Penduduk Miskin - September (ribu) (Ribu)', 'Persentase Penduduk Miskin - Maret', 'Persentase Penduduk Miskin - September', 'Unnamed: 7']

,Provinsi,Garis Kemiskinan - Maret (Rp),Garis Kemiskinan - September (Rp),Jumlah Penduduk Miskin - Maret (ribu) (Ribu),Jumlah Penduduk Miskin - September (ribu) (Ribu),Persentase Penduduk Miskin - Maret,Persentase Penduduk Miskin - September,Unnamed: 7
0,Aceh,676247,715103,704.69,703.33,12.33,12.22,NaN
1,Sumatera Utara,666546,718220,1140.25,1128.06,7.36,7.24,NaN
2,Sumatera Barat,729806,776517,312.35,312.3,5.35,5.31,NaN

====================================================================================================
FILE: Penduduk, Laju Pertumbuhan Penduduk, Distribusi Persentase Penduduk, Kepadatan Penduduk, Rasio Jenis Kelamin Penduduk Menurut Provinsi, 2025.xlsx
====================================================================================================
Sheet: ['Sheet1']

--- SHEET: Sheet1 ---
Shape: (52, 8)
Kolom:
['Provinsi', 'Jumlah Penduduk (Ribu)', 'Laju Pertumbuhan Penduduk per Tahun', 'Persentase Penduduk', 'Kepadatan Penduduk per km persegi (Km2)', 'Rasio Jenis Kelamin Penduduk', 'Unnamed: 6', 'Unnamed: 7']

,Provinsi,Jumlah Penduduk (Ribu),Laju Pertumbuhan Penduduk per Tahun,Persentase Penduduk,Kepadatan Penduduk per km persegi (Km2),Rasio Jenis Kelamin Penduduk,Unnamed: 6,Unnamed: 7
0,Aceh,5626,1.37,1.98,99,100.9,NaN,NaN
1,Sumatera Utara,15785.8,1.37,5.55,218,100.8,NaN,NaN
2,Sumatera Barat,5914.3,1.41,2.08,140,101.5,NaN,NaN

====================================================================================================
FILE: Pengeluaran per Kapita yang Disesuaikan menurut Jenis Kelamin, 2025.xlsx
====================================================================================================
Sheet: ['Sheet1']

--- SHEET: Sheet1 ---
Shape: (582, 3)
Kolom:
['Provinsi/Kabupaten/Kota/Indonesia', 'Unnamed: 1', 'Unnamed: 2']

,Provinsi/Kabupaten/Kota/Indonesia,Unnamed: 1,Unnamed: 2
0,NaN,Pengeluaran per Kapita yang Disesuaikan menuru...,NaN
1,NaN,Laki-laki,Perempuan
2,NaN,2025,2025

====================================================================================================
FILE: data_bencana_dampak_spesifik_2025.xlsx
====================================================================================================
Sheet: ['data_bencana_dampak_spesifik_20']

--- SHEET: data_bencana_dampak_spesifik_20 ---
Shape: (396, 11)
Kolom:
['Provinsi', 'Bulan', 'Tahun', 'Jenis Bencana', 'Jumlah Kejadian', 'Korban Meninggal (Jiwa)', 'Korban Hilang (Jiwa)', 'Korban Luka (Jiwa)', 'Korban Terdampak (Jiwa)', 'Korban Mengungsi (Jiwa)', 'Rumah Rusak (Unit)']

,Provinsi,Bulan,Tahun,Jenis Bencana,Jumlah Kejadian,Korban Meninggal (Jiwa),Korban Hilang (Jiwa),Korban Luka (Jiwa),Korban Terdampak (Jiwa),Korban Mengungsi (Jiwa),Rumah Rusak (Unit)
0,Aceh,Januari,2025,Banjir,3,0,0,6,840,204,30
1,Aceh,Januari,2025,Tanah Longsor,1,0,0,1,82,13,9
2,Aceh,Februari,2025,Banjir,2,0,0,2,722,135,8

====================================================================================================
FILE: Inflasi Tahunan (Y-on-Y) 38 Provinsi (2022=100), 2025.xlsx
====================================================================================================
Sheet: ['Sheet1']

--- SHEET: Sheet1 ---
Shape: (39, 14)
Kolom:
['38 Provinsi (2022=100)', 'Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember', 'Tahunan']

,38 Provinsi (2022=100),Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan
0,PROV ACEH,1.61,0.41,1.53,3.11,2.35,2.19,3.00,3.70,4.45,4.66,3.58,6.71,-
1,PROV SUMATERA UTARA,1.78,0.73,0.69,2.09,1.11,1.25,2.86,4.42,5.32,4.97,3.96,4.66,-
2,PROV SUMATERA BARAT,1.24,-0.09,0.30,2.38,0.85,0.45,2.19,2.89,4.22,4.52,3.98,5.15,-

In [7]:
!pip install -q duckdb pyarrow openpyxl

import re
import duckdb
import numpy as np
import pandas as pd
from pathlib import Path

# ====== KONFIGURASI (sesuaikan) ======
BASE  = Path("/content/drive/MyDrive/DM2_INFLASI")        # mis. Path("/content/drive/MyDrive/bps_2025")
RAW   = BASE / "/content/drive/MyDrive/DM2_INFLASI/data_lake"            # folder berisi semua .xlsx (subfolder boleh)
LAKE  = BASE / "/content/drive/MyDrive/DM2_INFLASI/data_lake/raw"           # output parquet per domain
DB    = BASE / "bps_2025.duckdb"
TAHUN = 2025

LAKE.mkdir(parents=True, exist_ok=True)
con = duckdb.connect(str(DB))

XLSX = {p.name: p for p in RAW.rglob("*.xlsx")}
print(len(XLSX), "file xlsx ditemukan")

def find(keyword):
    hits = [p for n, p in XLSX.items() if keyword.lower() in n.lower()]
    if len(hits) != 1:
        raise FileNotFoundError(f"'{keyword}' cocok dengan {len(hits)} file: {[h.name for h in hits]}")
    return hits[0]

BULAN_NAMA = ["Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli",
              "Agustus", "September", "Oktober", "November", "Desember"]
BULAN_MAP = {}
for i, n in enumerate(BULAN_NAMA, 1):
    BULAN_MAP[n.lower()] = i
    BULAN_MAP[n.lower()[:3]] = i
BULAN_MAP["ags"] = 8

ALIAS = {
    "SEMUA PROVINSI": "INDONESIA",
    "DAERAH ISTIMEWA YOGYAKARTA": "DI YOGYAKARTA",
    "D I YOGYAKARTA": "DI YOGYAKARTA",
    "DAERAH KHUSUS IBUKOTA JAKARTA": "DKI JAKARTA",
    "BANGKA BELITUNG": "KEPULAUAN BANGKA BELITUNG",
}

def norm_name(s):
    """Samakan penulisan nama provinsi: 'PROV ACEH', '11 Aceh', 'KEP. RIAU' -> kunci seragam."""
    s = str(s).upper()
    s = re.sub(r"^\s*\d+\s+", "", s)
    s = re.sub(r"^\s*(PROVINSI|PROV)\b\.?\s*", "", s)
    s = re.sub(r"\bKEP\b\.?", "KEPULAUAN", s)
    s = re.sub(r"[^A-Z0-9 ]", " ", s)
    s = re.sub(r"\s+", " ", s).strip()
    return ALIAS.get(s, s)

def to_num(s, thousands=","):
    """'12,750' -> 12750.0 ; '-' / '–' -> NaN"""
    if pd.api.types.is_numeric_dtype(s):
        return s.astype(float)
    x = s.astype(str).str.strip().str.replace(thousands, "", regex=False)
    x = x.replace({"-": np.nan, "–": np.nan, "—": np.nan, "": np.nan,
                   "nan": np.nan, "NaN": np.nan, "None": np.nan})
    return pd.to_numeric(x, errors="coerce")

def melt_bulan(df, value_name):
    """Tabel lebar (kolom = nama bulan) -> panjang (nama_wilayah, bulan_id, nilai)."""
    idc = df.columns[0]
    bcols = [c for c in df.columns[1:] if str(c).strip().lower() in BULAN_MAP]
    long = df.melt(id_vars=idc, value_vars=bcols, var_name="bulan_nama", value_name=value_name)
    bulan = long["bulan_nama"].astype(str).str.strip().str.lower().map(BULAN_MAP)
    long["bulan_id"] = TAHUN * 100 + bulan
    long[value_name] = to_num(long[value_name])
    long = long.rename(columns={idc: "nama_wilayah"})
    return long[["nama_wilayah", "bulan_id", value_name]].dropna(subset=[value_name])

def cek_unik(df, keys, nama):
    print(f"[cek] {nama}: {df.duplicated(subset=keys).sum()} duplikat pada kunci {keys}")

def save_table(df, domain, name):
    out = LAKE / domain
    out.mkdir(parents=True, exist_ok=True)
    df.to_parquet(out / f"{name}.parquet", index=False)
    con.register("_tmp", df)
    con.execute(f"CREATE OR REPLACE TABLE {name} AS SELECT * FROM _tmp")
    con.unregister("_tmp")
    print(f"{name:28s} {len(df):>7,} baris  ->  lake/{domain}/{name}.parquet")

19 file xlsx ditemukan

In [8]:
ump = pd.read_excel(find("Upah Minimum Provinsi"))
kn = ump.iloc[:, 0].astype(str).str.extract(r"^\s*(\d+)\s+(.+?)\s*$").dropna()
kn.columns = ["kode", "nama"]

WILAYAH = {1: "Sumatera", 2: "Sumatera", 3: "Jawa", 5: "Bali & Nusa Tenggara",
           6: "Kalimantan", 7: "Sulawesi", 8: "Maluku", 9: "Papua"}

dim_provinsi = pd.DataFrame({
    "kode_provinsi": kn["kode"].astype(int).values,
    "nama_provinsi": kn["nama"].str.strip().values,
}).sort_values("kode_provinsi")
dim_provinsi = pd.concat(
    [pd.DataFrame({"kode_provinsi": [0], "nama_provinsi": ["INDONESIA"]}), dim_provinsi],
    ignore_index=True)
dim_provinsi["wilayah"] = dim_provinsi["kode_provinsi"].map(
    lambda k: "Nasional" if k == 0 else WILAYAH.get(k // 10, "Lainnya"))
dim_provinsi["nama_key"] = dim_provinsi["nama_provinsi"].map(norm_name)

print("Jumlah provinsi (tanpa nasional):", len(dim_provinsi) - 1, "(harapan: 38)")
KEY2KODE = dict(zip(dim_provinsi["nama_key"], dim_provinsi["kode_provinsi"]))

def add_kode(df, col="nama_wilayah", sumber="", verbose=True):
    """Ganti nama wilayah dengan kode_provinsi; baris yang tidak cocok (catatan kaki, kab/kota) dibuang."""
    kode = df[col].map(norm_name).map(KEY2KODE)
    if verbose:
        tak = sorted(df.loc[kode.isna() & df[col].notna(), col].astype(str).unique())
        if tak:
            print(f"[{sumber}] {len(tak)} nama tidak cocok, dibuang: {tak[:6]}{' ...' if len(tak) > 6 else ''}")
    out = df.assign(kode_provinsi=kode)
    out = out[out["kode_provinsi"].notna()].astype({"kode_provinsi": "int"})
    return out.drop(columns=[col])

dim_waktu = pd.DataFrame({
    "bulan_id": [TAHUN * 100 + m for m in range(1, 13)],
    "tahun": TAHUN,
    "bulan": range(1, 13),
    "nama_bulan": BULAN_NAMA,
    "kuartal": [(m - 1) // 3 + 1 for m in range(1, 13)],
    "semester": [(m - 1) // 6 + 1 for m in range(1, 13)],
})

save_table(dim_provinsi.drop(columns="nama_key"), "Dimensi", "dim_provinsi")
save_table(dim_waktu, "Dimensi", "dim_waktu")

Jumlah provinsi (tanpa nasional): 38 (harapan: 38)
dim_provinsi                      39 baris  ->  lake/Dimensi/dim_provinsi.parquet
dim_waktu                         12 baris  ->  lake/Dimensi/dim_waktu.parquet

In [9]:
frames = []
for p in sorted(RAW.rglob("*Komoditas_*.xlsx")):
    komoditas = p.stem.split("Komoditas_")[-1].strip()
    df = pd.read_excel(p)
    df = df.rename(columns={df.columns[1]: "nama_wilayah"})
    long = df.melt(id_vars="nama_wilayah", value_vars=list(df.columns[2:]),
                   var_name="tanggal", value_name="harga_rp")
    txt = long["tanggal"].astype(str).str.replace(" ", "", regex=False)   # '01/ 01/ 2025' -> '01/01/2025'
    tgl = pd.to_datetime(txt, format="%d/%m/%Y", errors="coerce")
    long["tanggal_data"] = tgl.fillna(pd.to_datetime(long["tanggal"], errors="coerce"))
    long["harga_rp"] = to_num(long["harga_rp"])
    long["nama_komoditas"] = komoditas
    frames.append(long.drop(columns="tanggal"))

harga = pd.concat(frames, ignore_index=True).dropna(subset=["harga_rp", "tanggal_data"])
harga["bulan_id"] = harga["tanggal_data"].dt.year * 100 + harga["tanggal_data"].dt.month

dim_komoditas = pd.DataFrame({"nama_komoditas": sorted(harga["nama_komoditas"].unique())})
dim_komoditas.insert(0, "komoditas_id", range(1, len(dim_komoditas) + 1))
harga = harga.merge(dim_komoditas, on="nama_komoditas")

fact_harga = add_kode(harga, sumber="harga")[
    ["kode_provinsi", "komoditas_id", "bulan_id", "tanggal_data", "harga_rp"]]
cek_unik(fact_harga, ["kode_provinsi", "komoditas_id", "bulan_id"], "fact_harga")

save_table(dim_komoditas, "Pangan", "dim_komoditas")
save_table(fact_harga, "Pangan", "fact_harga")

[cek] fact_harga: 0 duplikat pada kunci ['kode_provinsi', 'komoditas_id', 'bulan_id']
dim_komoditas                      9 baris  ->  lake/Pangan/dim_komoditas.parquet
fact_harga                     2,898 baris  ->  lake/Pangan/fact_harga.parquet

In [10]:
tpt = pd.read_excel(find("Tingkat Pengangguran"))
fact_tpt = add_kode(melt_bulan(tpt, "tpt_pct"), sumber="tpt")
cek_unik(fact_tpt, ["kode_provinsi", "bulan_id"], "fact_tpt")

tpak = pd.read_excel(find("Angkatan Kerja"))
fact_tpak = add_kode(melt_bulan(tpak, "tpak_pct"), sumber="tpak")
cek_unik(fact_tpak, ["kode_provinsi", "bulan_id"], "fact_tpak")

fact_ump = pd.DataFrame({
    "kode_provinsi": kn["kode"].astype(int).values,
    "tahun": TAHUN,
    "ump_rp": to_num(ump.iloc[:, 1].loc[kn.index]).values,
})

# Rata-rata upah: per SEKTOR (nasional), bukan per provinsi
up = pd.read_excel(find("Rata-Rata Upah"))
fact_upah = melt_bulan(up, "upah_rp").rename(columns={"nama_wilayah": "sektor"})

save_table(fact_tpt, "Ekonomi", "fact_tpt")
save_table(fact_tpak, "Ekonomi", "fact_tpak")
save_table(fact_ump, "Ekonomi", "fact_ump")
save_table(fact_upah, "Ekonomi", "fact_upah_sektor_nasional")

[cek] fact_tpt: 0 duplikat pada kunci ['kode_provinsi', 'bulan_id']
[cek] fact_tpak: 0 duplikat pada kunci ['kode_provinsi', 'bulan_id']
fact_tpt                          78 baris  ->  lake/Ekonomi/fact_tpt.parquet
fact_tpak                         78 baris  ->  lake/Ekonomi/fact_tpak.parquet
fact_ump                          38 baris  ->  lake/Ekonomi/fact_ump.parquet
fact_upah_sektor_nasional         54 baris  ->  lake/Ekonomi/fact_upah_sektor_nasional.parquet

In [11]:
raw_e = pd.read_excel(find("Inflasi Bulanan"), header=None)

print("Cuplikan struktur file (12 baris x 8 kolom pertama):")
display(raw_e.iloc[:12, :8])

# Baris header bulan = baris dengan nama bulan terbanyak
n_bulan = raw_e.apply(
    lambda r: r.astype(str).str.strip().str.lower().map(BULAN_MAP).notna().sum(), axis=1)
mrow = int(n_bulan.idxmax())
SUB_OFFSET = 1        # label subkelompok ada di baris (mrow - SUB_OFFSET); ubah jika berbeda

sub_label = raw_e.iloc[mrow - SUB_OFFSET].ffill()
bulan_row = raw_e.iloc[mrow].astype(str).str.strip().str.lower().map(BULAN_MAP)

body = raw_e.iloc[mrow + 1:]
prov_col = int(body.apply(lambda c: c.astype(str).str.contains("ACEH", case=False).any()).idxmax())

rows = []
for j in raw_e.columns:
    if j > prov_col and pd.notna(bulan_row[j]):
        rows.append(pd.DataFrame({
            "nama_wilayah": body[prov_col].values,
            "subkelompok": str(sub_label[j]).strip(),
            "bulan_id": TAHUN * 100 + int(bulan_row[j]),
            "inflasi_mtm_pct": to_num(body[j]).values,
        }))

fact_inflasi_energi = add_kode(
    pd.concat(rows, ignore_index=True).dropna(subset=["inflasi_mtm_pct"]),
    sumber="inflasi_energi")
cek_unik(fact_inflasi_energi, ["kode_provinsi", "subkelompok", "bulan_id"], "fact_inflasi_energi")
print(fact_inflasi_energi["subkelompok"].value_counts())

save_table(fact_inflasi_energi, "Energi", "fact_inflasi_energi")

Cuplikan struktur file (12 baris x 8 kolom pertama):

,0,1,2,3,4,5,6,7
0,38 Provinsi (2022=100),Januari,Februari,Maret,April,Mei,Juni,Juli
1,PROV ACEH,-9.97,-3.73,9.25,5.86,0.1,-0.09,0.04
2,PROV SUMATERA UTARA,-7.11,-4.26,6.16,6.09,0.09,0.15,0.06
3,PROV SUMATERA BARAT,-7.56,-1.74,7.18,3.72,0.01,0.13,0.02
4,PROV RIAU,-10.11,-3.3,9.81,5.15,0.26,0.01,0.06
5,PROV JAMBI,-8.81,-5.49,8.15,7.82,0.04,0.04,0
6,PROV SUMATERA SELATAN,-8.35,-3.58,7.71,6.09,-0.01,-0.03,0.03
7,PROV BENGKULU,-10.13,-3.9,9.52,5.98,-0.12,0.04,0.02
8,PROV LAMPUNG,-11.7,-4.85,11.74,7.67,0.13,0.12,0.09
9,PROV KEPULAUAN BANGKA BELITUNG,-15.79,-0.2,19.03,0.06,0.01,-0.01,0.03
10,PROV KEPULAUAN RIAU,-2.23,-0.69,2.33,1.22,0.01,0.09,0.06
11,PROV DKI JAKARTA,-9.2,-1.39,8.22,6.45,0,0.01,0.05

[cek] fact_inflasi_energi: 154 duplikat pada kunci ['kode_provinsi', 'subkelompok', 'bulan_id']
subkelompok
0.06      272
0.09      233
0.05      195
0         192
0.02      154
0.1       117
0.08      117
0.03      117
-0.02      78
0.07       78
0.04       77
0.01       76
0.26       39
0.11       39
8.45       39
6.6        39
-9.16      39
-3.59      39
0.15       39
0.2        39
27.09      39
17.94      39
-13.23     39
-22.87     39
0.16       39
-0.01      39
0.21       38
8.08       38
Name: count, dtype: int64
fact_inflasi_energi            2,328 baris  ->  lake/Energi/fact_inflasi_energi.parquet

In [12]:
# Penduduk miskin (Maret & September)
ms = pd.read_excel(find("Penduduk Miskin"))
ms = ms.rename(columns={ms.columns[0]: "nama_wilayah"})
frames = []
for nama, m in [("Maret", 3), ("September", 9)]:
    frames.append(pd.DataFrame({
        "nama_wilayah": ms["nama_wilayah"],
        "bulan_id": TAHUN * 100 + m,
        "garis_kemiskinan_rp": to_num(ms[f"Garis Kemiskinan - {nama} (Rp)"]),
        "jumlah_miskin_ribu": to_num(ms[f"Jumlah Penduduk Miskin - {nama} (ribu) (Ribu)"]),
        "persen_miskin": to_num(ms[f"Persentase Penduduk Miskin - {nama}"]),
    }))
fact_miskin = add_kode(pd.concat(frames, ignore_index=True), sumber="miskin")
fact_miskin = fact_miskin.dropna(subset=["persen_miskin", "jumlah_miskin_ribu"], how="all")
cek_unik(fact_miskin, ["kode_provinsi", "bulan_id"], "fact_penduduk_miskin")

# Penduduk (tahunan)
pdk = pd.read_excel(find("Laju Pertumbuhan")).iloc[:, :6]
pdk.columns = ["nama_wilayah", "jumlah_penduduk_ribu", "laju_pertumbuhan_pct",
               "persen_penduduk", "kepadatan_km2", "rasio_jenis_kelamin"]
for c in pdk.columns[1:]:
    pdk[c] = to_num(pdk[c])
pdk["tahun"] = TAHUN
fact_penduduk = add_kode(pdk, sumber="penduduk").dropna(subset=["jumlah_penduduk_ribu"])
cek_unik(fact_penduduk, ["kode_provinsi", "tahun"], "fact_penduduk")

# Pengeluaran per kapita (file berisi provinsi + ratusan kab/kota; hanya baris provinsi dipakai)
pk = pd.read_excel(find("Pengeluaran per Kapita"), header=None).iloc[:, :3]
pk.columns = ["nama_wilayah", "pengeluaran_laki_rp", "pengeluaran_perempuan_rp"]
for c in pk.columns[1:]:
    pk[c] = to_num(pk[c])
pk["tahun"] = TAHUN
fact_pengeluaran = add_kode(pk, sumber="pengeluaran", verbose=False)
fact_pengeluaran = fact_pengeluaran.dropna(
    subset=["pengeluaran_laki_rp", "pengeluaran_perempuan_rp"], how="all")
cek_unik(fact_pengeluaran, ["kode_provinsi", "tahun"], "fact_pengeluaran_kapita")
print("Provinsi terdeteksi di file pengeluaran:", fact_pengeluaran["kode_provinsi"].nunique(), "(harapan: 38 + nasional)")

save_table(fact_miskin, "Sosial", "fact_penduduk_miskin")
save_table(fact_penduduk, "Sosial", "fact_penduduk")
save_table(fact_pengeluaran, "Sosial", "fact_pengeluaran_kapita")

[miskin] 4 nama tidak cocok, dibuang: ['Garis Kemiskinan (GK)', 'Indikator', 'Metadata Indikator', 'Persentase Penduduk Miskin (Headcount Index/P0)']
[cek] fact_penduduk_miskin: 0 duplikat pada kunci ['kode_provinsi', 'bulan_id']
[penduduk] 11 nama tidak cocok, dibuang: ['1Hasil Proyeksi Penduduk Indonesia 2020-2050 Hasil Sensus Penduduk 2020 (Pertengahan tahun/Juni)/ Indonesia Population Projection 2020-2050 Result of Population Census 2020 (mid year/June) ', '2Laju pertumbuhan penduduk dihitung berdasarkan penduduk tahun 2020 (September) dibandingkan dengan penduduk tahun 2025(Juni)/ The growth rate refers to the change of the population in 2020 (September) to the population in 2025 (June)  ', '3Luas provinsi berdasarkan Keputusan Menteri Dalam Negeri Nomor 100.1.1-6117 Tahun 2022 tanggal 9 November 2022/ Province area Based on Ministerial Decree of Home Affairs Number 100.1.1-6117,9 November 2022 ', '4 Laju pertumbuhan penduduk dihitung dengan menggunakan data dasar jumlah penduduk tahun 2020 yang merupakan penjumlahan dari kabupaten/kota pembentuk/ The Growth Rate calculated refers to total population 2020 is the sum of the forming regency/municipality ', 'Indikator', 'Jumlah Penduduk'] ...
[cek] fact_penduduk: 0 duplikat pada kunci ['kode_provinsi', 'tahun']
[cek] fact_pengeluaran_kapita: 1 duplikat pada kunci ['kode_provinsi', 'tahun']
Provinsi terdeteksi di file pengeluaran: 39 (harapan: 38 + nasional)
fact_penduduk_miskin              78 baris  ->  lake/Sosial/fact_penduduk_miskin.parquet
fact_penduduk                     39 baris  ->  lake/Sosial/fact_penduduk.parquet
fact_pengeluaran_kapita           40 baris  ->  lake/Sosial/fact_pengeluaran_kapita.parquet

In [18]:
# Bencana alam per provinsi (bulanan, detail dampak)
bp = pd.read_excel(find("bencana_dampak"))

# Bersihkan nama kolom agar seragam
bp.columns = [re.sub(r"\W+", "_", str(c).strip().lower()).strip("_") for c in bp.columns]

# Ubah kolom provinsi ke kode_provinsi
bp = bp.rename(columns={"provinsi": "nama_wilayah"})
fact_bencana_prov = add_kode(bp, col="nama_wilayah", sumber="bencana_provinsi")
fact_bencana_prov["tahun"] = TAHUN

# Pastikan tipe data numerik untuk kolom jumlah/dampak
numeric_cols = [c for c in fact_bencana_prov.columns if c not in ["nama_wilayah", "bulan", "jenis_bencana", "kode_provinsi"]]
for c in numeric_cols:
    fact_bencana_prov[c] = to_num(fact_bencana_prov[c]).fillna(0).astype(int)

cek_unik(fact_bencana_prov, ["kode_provinsi", "bulan", "jenis_bencana", "tahun"], "fact_bencana_provinsi")

# Membuat rekapitulasi tingkat nasional secara otomatis dengan aggregasi
rk = fact_bencana_prov.groupby(["jenis_bencana", "tahun"]).sum(numeric_only=True).reset_index()
rk = rk.drop(columns=["kode_provinsi"], errors="ignore")

# Inflasi tahunan (Y-on-Y) bulanan per provinsi
iy = pd.read_excel(find("Inflasi Tahunan"))
fact_inflasi_yoy = add_kode(melt_bulan(iy, "inflasi_yoy_pct"), sumber="inflasi_yoy")
cek_unik(fact_inflasi_yoy, ["kode_provinsi", "bulan_id"], "fact_inflasi_yoy")

save_table(fact_bencana_prov, "Bencana", "fact_bencana_provinsi")
save_table(rk, "Bencana", "fact_bencana_nasional")
save_table(fact_inflasi_yoy, "Inflasi", "fact_inflasi_yoy")

[cek] fact_bencana_provinsi: 0 duplikat pada kunci ['kode_provinsi', 'bulan', 'jenis_bencana', 'tahun']
[cek] fact_inflasi_yoy: 0 duplikat pada kunci ['kode_provinsi', 'bulan_id']
fact_bencana_provinsi            396 baris  ->  lake/Bencana/fact_bencana_provinsi.parquet
fact_bencana_nasional              4 baris  ->  lake/Bencana/fact_bencana_nasional.parquet
fact_inflasi_yoy                 468 baris  ->  lake/Inflasi/fact_inflasi_yoy.parquet

In [19]:
def slug(s):
    return re.sub(r"\W+", "_", s.lower()).strip("_")

kom = con.execute("SELECT komoditas_id, nama_komoditas FROM dim_komoditas ORDER BY 1").fetchall()
harga_cols = ",\n        ".join(
    f"MAX(CASE WHEN komoditas_id = {i} THEN harga_rp END) AS harga_{slug(n)}" for i, n in kom)

con.execute(f"""
CREATE OR REPLACE VIEW v_panel_provinsi_bulan AS
WITH harga AS (
    SELECT kode_provinsi, bulan_id,
        {harga_cols}
    FROM fact_harga
    GROUP BY 1, 2
),
bencana AS (
    SELECT kode_provinsi, tahun, SUM(jumlah_kejadian) AS total_bencana
    FROM fact_bencana_provinsi
    GROUP BY 1, 2
)
SELECT
    p.kode_provinsi, p.nama_provinsi, p.wilayah,
    w.bulan_id, w.tahun, w.bulan,
    h.* EXCLUDE (kode_provinsi, bulan_id),
    i.inflasi_yoy_pct,
    t.tpt_pct,
    k.tpak_pct,
    m.persen_miskin, m.jumlah_miskin_ribu, m.garis_kemiskinan_rp,
    u.ump_rp,
    d.jumlah_penduduk_ribu, d.kepadatan_km2,
    b.total_bencana
FROM dim_provinsi p
CROSS JOIN dim_waktu w
LEFT JOIN harga h                ON h.kode_provinsi = p.kode_provinsi AND h.bulan_id = w.bulan_id
LEFT JOIN fact_inflasi_yoy i     ON i.kode_provinsi = p.kode_provinsi AND i.bulan_id = w.bulan_id
LEFT JOIN fact_tpt t             ON t.kode_provinsi = p.kode_provinsi AND t.bulan_id = w.bulan_id
LEFT JOIN fact_tpak k            ON k.kode_provinsi = p.kode_provinsi AND k.bulan_id = w.bulan_id
LEFT JOIN fact_penduduk_miskin m ON m.kode_provinsi = p.kode_provinsi AND m.bulan_id = w.bulan_id
LEFT JOIN fact_ump u             ON u.kode_provinsi = p.kode_provinsi AND u.tahun = w.tahun
LEFT JOIN fact_penduduk d        ON d.kode_provinsi = p.kode_provinsi AND d.tahun = w.tahun
LEFT JOIN bencana b              ON b.kode_provinsi = p.kode_provinsi AND b.tahun = w.tahun
""")

print(con.execute("SHOW TABLES").df())
print(con.execute("""
    SELECT COUNT(*) AS baris, COUNT(DISTINCT kode_provinsi) AS provinsi,
           COUNT(DISTINCT bulan_id) AS bulan
    FROM v_panel_provinsi_bulan""").df())

con.execute("SELECT * FROM v_panel_provinsi_bulan WHERE kode_provinsi = 0 ORDER BY bulan_id").df().head(12)

                         name
0               dim_komoditas
1                dim_provinsi
2                   dim_waktu
3       fact_bencana_nasional
4       fact_bencana_provinsi
5                  fact_harga
6         fact_inflasi_energi
7            fact_inflasi_yoy
8               fact_penduduk
9        fact_penduduk_miskin
10    fact_pengeluaran_kapita
11                  fact_tpak
12                   fact_tpt
13                   fact_ump
14  fact_upah_sektor_nasional
15     v_panel_provinsi_bulan
   baris  provinsi  bulan
0    468        39     12

,kode_provinsi,nama_provinsi,wilayah,bulan_id,tahun,bulan,harga_ayam,harga_bawang_merah,harga_beras,harga_cabai_merah,...,inflasi_yoy_pct,tpt_pct,tpak_pct,persen_miskin,jumlah_miskin_ribu,garis_kemiskinan_rp,ump_rp,jumlah_penduduk_ribu,kepadatan_km2,total_bencana
0,0,INDONESIA,Nasional,202501,2025,1,29050.0,31400.0,12750.0,26450.0,...,0.76,NaN,NaN,NaN,NaN,NaN,NaN,284438.8,150.0,NaN
1,0,INDONESIA,Nasional,202502,2025,2,28050.0,25550.0,12650.0,39150.0,...,-0.09,4.76,70.60,NaN,NaN,NaN,NaN,284438.8,150.0,NaN
2,0,INDONESIA,Nasional,202503,2025,3,26400.0,23750.0,12650.0,36550.0,...,1.03,NaN,NaN,8.47,23854.56,609160.0,NaN,284438.8,150.0,NaN
3,0,INDONESIA,Nasional,202504,2025,4,26200.0,31650.0,12900.0,36200.0,...,1.95,NaN,NaN,NaN,NaN,NaN,NaN,284438.8,150.0,NaN
4,0,INDONESIA,Nasional,202505,2025,5,24300.0,32550.0,12850.0,40900.0,...,1.60,NaN,NaN,NaN,NaN,NaN,NaN,284438.8,150.0,NaN
5,0,INDONESIA,Nasional,202506,2025,6,25700.0,26750.0,12950.0,31850.0,...,1.87,NaN,NaN,NaN,NaN,NaN,NaN,284438.8,150.0,NaN
6,0,INDONESIA,Nasional,202507,2025,7,24800.0,32100.0,13100.0,30700.0,...,2.37,NaN,NaN,NaN,NaN,NaN,NaN,284438.8,150.0,NaN
7,0,INDONESIA,Nasional,202508,2025,8,26400.0,33900.0,13550.0,33100.0,...,2.31,4.85,70.59,NaN,NaN,NaN,NaN,284438.8,150.0,NaN
8,0,INDONESIA,Nasional,202509,2025,9,26200.0,36500.0,13600.0,29100.0,...,2.65,NaN,NaN,8.25,23359.71,641443.0,NaN,284438.8,150.0,NaN
9,0,INDONESIA,Nasional,202510,2025,10,28750.0,29850.0,13550.0,39150.0,...,2.86,NaN,NaN,NaN,NaN,NaN,NaN,284438.8,150.0,NaN
10,0,INDONESIA,Nasional,202511,2025,11,28900.0,29100.0,13550.0,36900.0,...,2.72,NaN,NaN,NaN,NaN,NaN,NaN,284438.8,150.0,NaN
11,0,INDONESIA,Nasional,202512,2025,12,29050.0,29850.0,13300.0,36900.0,...,2.92,NaN,NaN,NaN,NaN,NaN,NaN,284438.8,150.0,NaN